export const SET_INTRO_TOGGLE = "SET_INTRO_TOGGLE";
export const SET_CHOOSE_PROFILE_VISIBILITY = "SET_CHOOSE_PROFILE_VISIBILITY";
export const SET_AUTH_CLIENT_ID = "SET_AUTH_CLIENT_ID";
export const SET_SUCCESSFUL_LOGIN = "SET_SUCCESSFUL_LOGIN";
export const SET_APP_MESSAGE = "SET_APP_MESSAGE";
export const SET_HOME_SCREEN_VISIBLE = "SET_HOME_SCREEN_VISIBLE";
export const SET_HOME_SCREEN_NO_OF_WORK = "SET_HOME_SCREEN_NO_OF_WORK";
export const SET_DEVICE_LOCATION = "SET_DEVICE_LOCATION";
export const SET_DRIVER_EARNING_VALUE = "SET_DRIVER_EARNING_VALUE";
export const SET_APP_LANGUAGE = "SET_APP_LANGUAGE";
export const SET_LOGOUT = "SET_LOGOUT";
export const SET_DRIVER_JOB_OFFERS = "SET_DRIVER_JOB_OFFERS";
export const SET_MAIN_SCREEN_WORK_SCHEDULE = "SET_MAIN_SCREEN_WORK_SCHEDULE";
export const SET_MAIN_SCREEN_DRIVER_HOURLY_PAY =
	"SET_MAIN_SCREEN_DRIVER_HOURLY_PAY";
export const SET_MAIN_SCREEN_DRIVER_WEEKLY_PAY =
	"SET_MAIN_SCREEN_DRIVER_WEEKLY_PAY";
export const SET_MAIN_SCREEN_DRIVER_MONTHLY_PAY =
	"SET_MAIN_SCREEN_DRIVER_MONTHLY_PAY";
export const SET_MAIN_SCREEN_DRIVER_KM_PAY = "SET_MAIN_SCREEN_DRIVER_KM_PAY";
export const SET_MAIN_SCREEN_DRIVER_TRIP_PAY =
	"SET_MAIN_SCREEN_DRIVER_TRIP_PAY";
export const SET_MAIN_SCREEN_EXPERIENCE = "SET_MAIN_SCREEN_EXPERIENCE";
export const SET_MAIN_SCREEN_DRIVER_VEHICLE_PREFERENCE =
	"SET_MAIN_SCREEN_DRIVER_VEHICLE_PREFERENCE";
export const SET_MAIN_SCREEN_OWNER_VEHICLE_PREFERENCE =
	"SET_MAIN_SCREEN_OWNER_VEHICLE_PREFERENCE";
export const SAVE_MAIN_SCREEN_OWNER_VEHICLE_PREFERENCE =
	"SAVE_MAIN_SCREEN_OWNER_VEHICLE_PREFERENCE";
export const SAVE_MAIN_SCREEN_OWNER_DRIVER_QUALIFICATION =
	"SAVE_MAIN_SCREEN_OWNER_DRIVER_QUALIFICATION";
export const SAVE_MAIN_SCREEN_OWNER_WORK_SCHEDULE =
	"SAVE_MAIN_SCREEN_OWNER_WORK_SCHEDULE";
export const SET_MAIN_SCREEN_PERSONAL_DETAILS =
	"SET_MAIN_SCREEN_PERSONAL_DETAILS";
export const SAVE_MAIN_SCREEN_OWNER_DRIVER_PAY_SCALE =
	"SAVE_MAIN_SCREEN_OWNER_DRIVER_PAY_SCALE";
export const RESET_OWNER_JOB_POST = "RESET_OWNER_JOB_POST";
export const SET_OWNER_ADS_INDEX = "SET_OWNER_ADS_INDEX";
export const SET_OWNER_DASHBOARD = "SET_OWNER_DASHBOARD";
export const OWNER_JOB_DETAIL_BY_ID = "OWNER_JOB_DETAIL_BY_ID";
export const OWNER_FIND_DRIVERS_BY_ID = "OWNER_FIND_DRIVERS_BY_ID";
export const SET_FILTERED_HOME_WORK_DATA = "SET_FILTERED_HOME_WORK_DATA";
export const SET_DRIVER_JOB_OFFERS_FOR_DRIVER =
	"SET_DRIVER_JOB_OFFERS_FOR_DRIVER";
export const OWNER_LEASE_FIRM_BY_ID = "OWNER_LEASE_FIRM_BY_ID";
export const OWNER_FIND_LEASE_FIRM_BY_ID = "OWNER_FIND_LEASE_FIRM_BY_ID";
export const SET_LEASE_DASHBOARD = "SET_LEASE_DASHBOARD";
export const LEASE_FIND_ALL_OWNER_BY_ID = "LEASE_FIND_ALL_OWNER_BY_ID";
export const LEASE_FIRM_JOBS = "LEASE_FIRM_JOBS";
export const GET_OWNER_POST = "GET_OWNER_POST";
export const LEASE_FIRM_POSTED_ADS = "LEASE_FIRM_POSTED_ADS";
export const RESET_AUTH = "RESET_AUTH";
export const RESET_DRIVER = "RESET_DRIVER";
export const SET_MAIN_SCREEN_LEASE_VEHICLE_PREFERENCE =
	"SET_MAIN_SCREEN_LEASE_VEHICLE_PREFERENCE";
export const SAVE_LEASE_FIRM_VEHICLE_DETAILS =
	"SAVE_LEASE_FIRM_VEHICLE_DETAILS";
export const SAVE_LEASE_CONTRACT_DETAILS = "SAVE_LEASE_CONTRACT_DETAILS";
export const SAVE_LEASE_PAY_SCALE = "SAVE_LEASE_PAY_SCALE";
export const RESET_HOME='RESET_HOME'
export const SAVE_DRIVER_EXPERIENCE='SAVE_DRIVER_EXPERIENCE'
export const RESET_MAIN_REDUCER='RESET_MAIN_REDUCER'
export const SAVE_SUBSCRIPTION_AFTER_PAYMENT='SAVE_SUBSCRIPTION_AFTER_PAYMENT'
export const SET_USER_SUBSCRIPTION='SET_USER_SUBSCRIPTION'
export const RESET_SUBSCRIPTION='RESET_SUBSCRIPTION'
export const RESET_PROFILE_VISIBILITY='RESET_PROFILE_VISIBILITY'
